wip
Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -62,20 +62,20 @@ jobs:
       die "Failed to build git-credential-osxkeychain"
 
       # see https://stackoverflow.com/questions/1365211/error-in-xcode-project-ld-library-not-found-for-lcrt1-10-6-o/16102800, to fix the -lcrt1.10.6.o problem
-      PLATFORMS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms
-      OSX_SDK_DIR=$PLATFORMS_DIR/MacOSX.platform/Developer/SDKs/MacOSX.sdk
-      export C_INCLUDE_PATH=$OSX_SDK_DIR/usr/include
-      export LIBRARY_PATH=$OSX_SDK_DIR/usr/lib
+      #      PLATFORMS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms
+      #OSX_SDK_DIR=$PLATFORMS_DIR/MacOSX.platform/Developer/SDKs/MacOSX.sdk
+      #export C_INCLUDE_PATH=$OSX_SDK_DIR/usr/include
+      #export LIBRARY_PATH=$OSX_SDK_DIR/usr/lib
 
       # work around the frameworks not being visible when compiling with -isysroot $OSX_SDK_DIR
-      sed -i .bak -e 's/osxkeychain.*SUBMAKE.*/& LDFLAGS="\$(LDFLAGS) -iframework \/System\/Library\/Frameworks\/"/' Makefile ||
-      die "Could not edit Makefile"
-      mkdir -p include
-      test -h include/Security ||
-      ln -s /System/Library/Frameworks/Security.framework/Headers/ include/Security
-      test -h include/CoreFoundation ||
-      ln -s /System/Library/Frameworks//CoreFoundation.framework/Versions/A/Headers/ include/CoreFoundation
-      export C_INCLUDE_PATH=$C_INCLUDE_PATH:$PWD/include
+      #sed -i .bak -e 's/osxkeychain.*SUBMAKE.*/& LDFLAGS="\$(LDFLAGS) -iframework \/System\/Library\/Frameworks\/"/' Makefile ||
+      #die "Could not edit Makefile"
+      #mkdir -p include
+      #test -h include/Security ||
+      #ln -s /System/Library/Frameworks/Security.framework/Headers/ include/Security
+      #test -h include/CoreFoundation ||
+      #ln -s /System/Library/Frameworks//CoreFoundation.framework/Versions/A/Headers/ include/CoreFoundation
+      #export C_INCLUDE_PATH=$C_INCLUDE_PATH:$PWD/include
 
       # make sure that .../usr/local/git/share/man/ exists
       sed -i .bak -e 's/\(tar .*-C \)\(.*\/share\/man\)$/mkdir -p \2 \&\& &/' \
@@ -90,7 +90,7 @@ jobs:
       #die "Build failed"
 
       PATH=/usr/local/bin:$PATH \
-      make OSX_VERSION=10.6 C_INCLUDE_PATH="$C_INCLUDE_PATH" V=1 image ||
+      make OSX_VERSION=10.6 V=1 image ||
       die "Build failed"
 
       mv *.dmg "$(Build.ArtifactStagingDirectory)"/
